name       : mtr
version    : 0.86
release    : 1
source     :
    - ftp://ftp.bitwizard.nl/mtr/mtr-0.86.tar.gz : c5d948920b641cc35f8b380fc356ddfe07cce6a9c6474afe242fc58113f28c06
license    : GPL-2.0
summary    : Combines the functionality of traceroute and ping into one tool (CLI version)
description: |
    Combines the functionality of traceroute and ping into one tool (CLI version)
builddeps  :
setup      : |
    %configure --sbindir=/usr/bin
build      : |
    %make
install    : |
    %make_install
