name       : mtr
version    : '0.94'
release    : 6
source     :
    - https://github.com/traviscross/mtr/archive/refs/tags/v0.94.tar.gz : ea036fdd45da488c241603f6ea59a06bbcfe6c26177ebd34fff54336a44494b8
license    : GPL-2.0-or-later
component  : network.utils
summary    : Combines the functionality of traceroute and ping into one tool (CLI version)
description: |
    Combines the functionality of traceroute and ping into one tool (CLI version)
builddeps  :
    - pkgconfig(libcap)
setup      : |
    echo $version > .tarball-version
    %reconfigure --sbindir=/usr/bin --without-gtk
build      : |
    %make
install    : |
    %make_install
