name       : mtr
version    : '0.93'
release    : 5
source     :
    - https://github.com/traviscross/mtr/archive/v0.93.tar.gz : 3a1ab330104ddee3135af3cfa567b9608001c5deecbf200c08b545ed6d7a4c8f
license    : GPL-2.0-or-later
component  : network.utils
summary    : Combines the functionality of traceroute and ping into one tool (CLI version)
description: |
    Combines the functionality of traceroute and ping into one tool (CLI version)
builddeps  :
    - pkgconfig(libcap)
setup      : |
    echo $version > .tarball-version
    %reconfigure --sbindir=/usr/bin --without-gtk
build      : |
    %make
install    : |
    %make_install
