name       : mtr
version    : '0.92'
release    : 3
source     :
    - https://github.com/traviscross/mtr/archive/v0.92.tar.gz : 568a52911a8933496e60c88ac6fea12379469d7943feb9223f4337903e4bc164
license    : GPL-2.0-or-later
component  : network.utils
summary    : Combines the functionality of traceroute and ping into one tool (CLI version)
description: |
    Combines the functionality of traceroute and ping into one tool (CLI version)
builddeps  :
    - pkgconfig(libcap)
setup      : |
    %reconfigure --sbindir=/usr/bin --without-gtk
build      : |
    %make
install    : |
    %make_install
