name       : mtr
version    : 0.92
release    : 2
source     :
    - ftp://ftp.bitwizard.nl/mtr/mtr-0.92.tar.gz : f2979db9e2f41aa8e6574e7771767c9afe111d9213814eb47f5e1e71876e4382
license    : GPL-2.0
component  : network.utils
summary    : Combines the functionality of traceroute and ping into one tool (CLI version)
description: |
    Combines the functionality of traceroute and ping into one tool (CLI version)
builddeps  :
    - pkgconfig(libcap)
setup      : |
    %configure --sbindir=/usr/bin --without-gtk
build      : |
    %make
install    : |
    %make_install
